//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mimeo.DynamicUI.Blazor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mimeo.DynamicUI.Blazor.DefaultLanguage", typeof(DefaultLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string actions {
            get {
                return ResourceManager.GetString("actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Filter.
        /// </summary>
        internal static string datafilter_addfilter {
            get {
                return ResourceManager.GetString("datafilter_addfilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string datafilter_searchtextplaceholder {
            get {
                return ResourceManager.GetString("datafilter_searchtextplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact Date.
        /// </summary>
        internal static string datefilteroption_exact {
            get {
                return ResourceManager.GetString("datefilteroption_exact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 Days Ago.
        /// </summary>
        internal static string datefilteroption_sevendaysago {
            get {
                return ResourceManager.GetString("datefilteroption_sevendaysago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 Days From Now.
        /// </summary>
        internal static string datefilteroption_sevendaysfromnow {
            get {
                return ResourceManager.GetString("datefilteroption_sevendaysfromnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Days Ago.
        /// </summary>
        internal static string datefilteroption_thirtydaysago {
            get {
                return ResourceManager.GetString("datefilteroption_thirtydaysago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Days From Now.
        /// </summary>
        internal static string datefilteroption_thirtydaysfromnow {
            get {
                return ResourceManager.GetString("datefilteroption_thirtydaysfromnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string datefilteroption_today {
            get {
                return ResourceManager.GetString("datefilteroption_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string datefilteroption_tomorrow {
            get {
                return ResourceManager.GetString("datefilteroption_tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Days From Now.
        /// </summary>
        internal static string datefilteroption_xdaysfromnow {
            get {
                return ResourceManager.GetString("datefilteroption_xdaysfromnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string datefilteroption_yesterday {
            get {
                return ResourceManager.GetString("datefilteroption_yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        internal static string datetimeformat {
            get {
                return ResourceManager.GetString("datetimeformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string datetimeformat_dateonly {
            get {
                return ResourceManager.GetString("datetimeformat_dateonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        internal static string datetimeformat_long {
            get {
                return ResourceManager.GetString("datetimeformat_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete this?.
        /// </summary>
        internal static string dynamiceditform_deleteconfirm_defaulttext {
            get {
                return ResourceManager.GetString("dynamiceditform_deleteconfirm_defaulttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string dynamiceditform_deleteconfirm_defaulttitle {
            get {
                return ResourceManager.GetString("dynamiceditform_deleteconfirm_defaulttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        internal static string filteroperator_contains {
            get {
                return ResourceManager.GetString("filteroperator_contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not contain.
        /// </summary>
        internal static string filteroperator_doesnotcontain {
            get {
                return ResourceManager.GetString("filteroperator_doesnotcontain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ends with.
        /// </summary>
        internal static string filteroperator_endswith {
            get {
                return ResourceManager.GetString("filteroperator_endswith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        internal static string filteroperator_equals {
            get {
                return ResourceManager.GetString("filteroperator_equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string filteroperator_greaterthan {
            get {
                return ResourceManager.GetString("filteroperator_greaterthan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        internal static string filteroperator_greaterthanorequals {
            get {
                return ResourceManager.GetString("filteroperator_greaterthanorequals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        internal static string filteroperator_in {
            get {
                return ResourceManager.GetString("filteroperator_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is all of.
        /// </summary>
        internal static string filteroperator_isallof {
            get {
                return ResourceManager.GetString("filteroperator_isallof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is any of.
        /// </summary>
        internal static string filteroperator_isanyof {
            get {
                return ResourceManager.GetString("filteroperator_isanyof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is between.
        /// </summary>
        internal static string filteroperator_isbetween {
            get {
                return ResourceManager.GetString("filteroperator_isbetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is empty.
        /// </summary>
        internal static string filteroperator_isempty {
            get {
                return ResourceManager.GetString("filteroperator_isempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is none of.
        /// </summary>
        internal static string filteroperator_isnoneof {
            get {
                return ResourceManager.GetString("filteroperator_isnoneof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not empty.
        /// </summary>
        internal static string filteroperator_isnotempty {
            get {
                return ResourceManager.GetString("filteroperator_isnotempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not null.
        /// </summary>
        internal static string filteroperator_isnotnull {
            get {
                return ResourceManager.GetString("filteroperator_isnotnull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is null.
        /// </summary>
        internal static string filteroperator_isnull {
            get {
                return ResourceManager.GetString("filteroperator_isnull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is on.
        /// </summary>
        internal static string filteroperator_ison {
            get {
                return ResourceManager.GetString("filteroperator_ison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string filteroperator_lessthan {
            get {
                return ResourceManager.GetString("filteroperator_lessthan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        internal static string filteroperator_lessthanorequals {
            get {
                return ResourceManager.GetString("filteroperator_lessthanorequals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not.
        /// </summary>
        internal static string filteroperator_notequals {
            get {
                return ResourceManager.GetString("filteroperator_notequals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not contain.
        /// </summary>
        internal static string filteroperator_notin {
            get {
                return ResourceManager.GetString("filteroperator_notin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts with.
        /// </summary>
        internal static string filteroperator_startswith {
            get {
                return ResourceManager.GetString("filteroperator_startswith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate GUID.
        /// </summary>
        internal static string generateguid {
            get {
                return ResourceManager.GetString("generateguid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results to display..
        /// </summary>
        internal static string grid_no_results {
            get {
                return ResourceManager.GetString("grid_no_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Count: {0}.
        /// </summary>
        internal static string grid_totalcount {
            get {
                return ResourceManager.GetString("grid_totalcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this form to import your data changes into the database. Be aware that changes will be executed immediately, and there is no rollback for this operation..
        /// </summary>
        internal static string importdialog_desc {
            get {
                return ResourceManager.GetString("importdialog_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported {0} rows. Time elapsed: {1:hh\:mm\:ss}..
        /// </summary>
        internal static string importdialog_progress {
            get {
                return ResourceManager.GetString("importdialog_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported {0} rows. Time elapsed: {1:hh\:mm\:ss}. Estimated {2:hh\:mm\:ss} remaining..
        /// </summary>
        internal static string importdialog_progresswithestimate {
            get {
                return ResourceManager.GetString("importdialog_progresswithestimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string importdialog_title {
            get {
                return ResourceManager.GetString("importdialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items selected.
        /// </summary>
        internal static string multiselectdropdown_placeholder {
            get {
                return ResourceManager.GetString("multiselectdropdown_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 item selected.
        /// </summary>
        internal static string multiselectdropdown_placeholder_single {
            get {
                return ResourceManager.GetString("multiselectdropdown_placeholder_single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
