# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:        
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.2.1
      with:
        versionSpec: '5.2.x'

    - name: Determine Version
      id: gitversion # step id used as a reference for output values
      uses: gittools/actions/gitversion/execute@v3.2.1
      with:
        useConfigFile: true

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Pack DynamicUI
      run: dotnet pack Mimeo.DynamicUI/Mimeo.DynamicUI.csproj --no-restore -c Release -o nuget -p:Version=${{ steps.gitversion.outputs.semVer }}

    - name: Pack DynamicUI.Blazor
      run: dotnet pack Mimeo.DynamicUI.Blazor/Mimeo.DynamicUI.Blazor.csproj --no-restore -c Release -o nuget -p:Version=${{ steps.gitversion.outputs.semVer }}
    
    - name: Upload nuget packages as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget
        path: nuget

    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
      
